### ISSUE TITLE
Miredo incompatiblity?  resulting in ipv4 oddity

### ISSUE THREAD

**Issue by faddat** [TheUbuntuGuy/dyndistcc#3]
![image](https://cloud.githubusercontent.com/assets/7142025/15308425/41df49e4-1c07-11e6-9f01-804c06b24612.png)

**Comment by faddat** [comment]
Still happening after removing miredo.  Going to pull the code you pushed and try it out with that now.

**Comment by TheUbuntuGuy** [comment]
This is a node.js issue: https://github.com/nodejs/node-v0.x-archive/issues/9195

**Comment by faddat** [comment]
So for your hosts, just disabled ipv6?  I'm not even really sure how to do that 

/me scurries to ubuntu man pages....

So, scurried, learned, and still croaking on me.  brb after a reboot....
